[build]
target = ["aarch64-apple-ios-macabi"]

[env]
# Same as `rustc --target=aarch64-apple-ios-macabi --print deployment-target`.
# Should be redundant after https://github.com/rust-lang/rust/issues/136113.
IPHONEOS_DEPLOYMENT_TARGET = "13.1"

# Mac Catalyst uses the macOS SDK
# Should be redundant after https://github.com/RustAudio/coreaudio-rs/pull/128.
COREAUDIO_SDK_PATH = "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk"

[patch."https://github.com/madsmtm/bevy"]
bevy_a11y = { path = "../bevy/crates/bevy_a11y" }
bevy_app = { path = "../bevy/crates/bevy_app" }
bevy_derive = { path = "../bevy/crates/bevy_derive" }
bevy_ecs = { path = "../bevy/crates/bevy_ecs" }
bevy_input = { path = "../bevy/crates/bevy_input" }
bevy_log = { path = "../bevy/crates/bevy_log" }
bevy_math = { path = "../bevy/crates/bevy_math" }
bevy_reflect = { path = "../bevy/crates/bevy_reflect" }
bevy_window = { path = "../bevy/crates/bevy_window" }
bevy_tasks = { path = "../bevy/crates/bevy_tasks" }
bevy = { path = "../bevy" }
