name: CI

on: [push]

permissions:
  contents: read

env:
  IPHONEOS_DEPLOYMENT_TARGET: 10.0

jobs:
  fmt:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: cargo fmt
      run: cargo fmt -- --check

  test:
    name: Test
    runs-on: macos-15 # Aarch64
    steps:
    - uses: actions/checkout@v4
    - uses: Swatinem/rust-cache@v2
    - run: cargo test
